name: local-gateway

services:
  gateway:
    image: traefik:v3.7.8
    command:
      - --configFile=/etc/traefik/traefik.yml
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 1s
    labels:
      local-gateway: "true"
    ports:
      - "127.0.0.1:80:80"
    restart: unless-stopped
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - local-gateway

networks:
  local-gateway:
    name: local-gateway
